module.exports = {
    "all" : 0,
    "Local" : 1,
    "Friends": 2,
    "Parenting" : 3,
    "School and Education" : 4,
    "Sports" : 5,
    "Food" : 6,
    "Photography" : 7,
    "Buy and Sell" : 8,
    "Professional Networking" : 9,
    "Animals and Pets" : 10,
    "Outdoor Activities" : 11,
    "Business" : 12,
    "Hobby and Leisure" : 13,
    "Science and Tech" : 14,
    "Health and Fitness" : 15,
    "Funny" : 16,
    "Arts and Culture" : 17,
    "Games" : 18,
    "Cars and Motorcycles" : 19,
    "Neighborhood and Community" : 20,
    "Support and Comfort" : 21,
    "Home and Garden" : 22,
    "Style" : 23,
    "Travel and Places" : 24,
    "Spiritual and Inspirational" : 25,
    "Movies and TV" : 26,
    "Trending" : 27,
    "Suggested" : 28
}